name: front-end CI with jest

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build --if-present

  Unit-Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Jest coverage report
        if: always()
        uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
          test-script: npm test

  SonarScan:
    needs: Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
