name: SonarCloud quality check

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
    types: [opened, synchronize, reopened]

jobs:
  SonarCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
